### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by ghost** [chetachiezikeuzor/MySnippets-Plugin#18]
I'm on v0.15.9 on Windows 10

After updating the plugin to the latest version on a test vault, the plugin completely stopped working. Clicking on the snippets icon on the status bar does nothing.

**Comment by thelegend09** [comment]
Same here.

**Comment by Archie-2021** [comment]
I just realized that it is not longer working for me too, probably broken on last obsidian update and I didn't noticed till now. Please fix this awesome plugin.

Thanks

**Comment by ksdavidc** [comment]
I can confirm that this (the popup not showing) stopped working after 1.2.1
I had this on two systems, one had 1.2.3, the other 1.2.1, and only 1.2.1 worked. On the first, using Brat I tried 1.2.2 and no go. 1.2.1 worked, though.

**Comment by ksdavidc** [comment]
also, bottom bar missing.

**Comment by nevertoday** [comment]
also, bottom bar missing.

**Comment by nihitkhandelwal-eng** [comment]
It works in one of my vaults but not in others.
I have disabled all other css snippets & plugins to rule out why this is happening, but I cannot figure it out.

**Comment by andrezgz** [comment]
Same here. Nothing happens when clicking on the snippets icon on the status bar.

Console log error, at least, for me:

```js
Uncaught TypeError: menu.setUseNativeMenu is not a function
    at snippetsMenu (plugin:mysnippets-plugin:114:14)
    at HTMLDivElement.eval (plugin:mysnippets-plugin:349:13)
```

This is the function related to the error:

```js
function snippetsMenu(app, plugin, settings) {
    const windowX = window.innerWidth;
    const windowY = window.innerHeight;
    const menuExists = document.querySelector(".menu.MySnippets-statusbar-menu");
    if (!menuExists) {
        const menu = new obsidian.Menu();
        menu.setUseNativeMenu(false);
        ...
```

**Comment by Gentleman03** [comment]
If you're using obsidian version lower than 0.16, use 1.2.1 version and everything should be working fine.

**Comment by ksdavidc** [comment]
There's a version .16???? Last one I see is .15.9

**Comment by Gentleman03** [comment]
> There's a version .16???? Last one I see is .15.9

Many people are insiders and already have 0.16, official is still 0.15 but plugins are already updated to work with 0.16 and many plugins that works with 0.16 doesn't work with 0.15. If plugin doesn't have limitation for updating it to latest version if you're still using 0.15 then some plugins stops working.

**Comment by gkavboy** [comment]
stopped working!!
